script:
- true
before_deploy: bash scripts/build.sh
deploy:
  provider: releases
  api_key:
    secure: ostiD+hd64+kzk1nIihkoQx2sQ8X0qNQI9xJK5+58nuzoQCYI/jGvLRH/ImYSBa9Ga/pLre/ZjUqTuuB1SUXUS3JNfleprRY7Gi6Xv4GMs/asrYkcrV1JbAHfJD7WcOKaIXUOy44cqcMMYXuKRk3V4UrCayHPiwMIV6eJ9vLnY7o72qBLx0DkvgMCr/N3GrHKzPECF+fw8yExEBxTCl9LjZyZ7ZDaECH+57mRPv5t67RSE6m9Eod7jVSjT9l+liEfHI9nlebu5MiGfEHrn0/OsD1YsBLzXKprxhxWIXWtjf9aahmwbzw8UVyTGlpgz7Myrva1fFC2Q5ntw1UhpiCiyIpx6QqX8vNBv6+aZP4fB4aJRsdWu+t7uQon1sWhGR/BZlIn1uvYf8+fJv7jgVJ0jNRQAwm0oW940MttTwP+Pz4rrZE3zcaPhH17g9hLd7vXTMForjr/CIFySxGvAfOfIoWYMKXqvEux8/3yX9osykYQ+2VcRhYL6pB0yuRI+YN4HFjrvVxAZECuarulqvSiWLGLMIaTPzm45GARsXxk5GB8NeB5cPgwHcQAKdI4bttfgfZcV83RXosm3/lEAOj3vyX/7IZh2paY5hiz/iThvFmEh9DfKQKLbp5EpHtNgdaYBKB+Yshq2Ax2KGvH8fenZKO38Vl/jTMCyFaqw8kz30=
  file:
  - release.zip
  - release.tgz
  skip_cleanup: true
  on:
    tags: true
